# Generated by Django 5.1.4 on 2025-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Solution')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
    ]
