# Generated by Django 5.1.4 on 2025-01-12 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeblock',
            name='created_time',
        ),
        migrations.AddField(
            model_name='codeblock',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
